### ISSUE TITLE
Internal fb info on public page

### ISSUE THREAD

**Issue by fairyteller** [hhvm/user-documentation#1019]
# Where is the problem?

Please check selected part
![image](https://user-images.githubusercontent.com/13288288/114373509-900cb780-9b7a-11eb-9af6-1335a90f4589.png)

# What is the problem?

Seems like this info should not be part of public documentation

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: HHVM=HHVM-4.102.0:HSL=v4.94.0:2021-04-09T18:33:31+0000:1fa47f258c6b68f8ec01899aa82fd6ffa0957109
 - Page requested: /hack/getting-started/input-and-output
 - Page requested at: Mon, 12 Apr 2021 09:23:39 +0000
 - Controller: GuidePageController

**Comment by fredemmott** [comment]
- we don't consider this information confidential, and we'd rather have FB employees use the public docs, and help improve them, rather than create/improve internal wiki pages
- this information is only supposed to appear if you are on an FB-owned IP address, e.g. FB corporate wifi or VPN; at least on my personal internet connection, this is not visible, so this appears to be working. In the source, this is `class="fbOnly"`

For this purpose, we consider the following prefixes to be FB-owned IP addresses:
- https://bgp.he.net/AS54115#_prefixes
- https://bgp.he.net/AS54115#_prefixes6
