### ISSUE TITLE
.hhconfig documentation

### ISSUE THREAD

**Issue by connordoner** [hhvm/user-documentation#1029]
Is there any documentation on options in .hhconfig, please?

**Comment by lexidor** [comment]
It would indeed be a good move to document these settings. I reverse engineered what most of them do from this exhaustive list. https://github.com/facebook/hhvm/blob/master/hphp/hack/src/options/globalOptions.ml

**Comment by lexidor** [comment]
Living the 4.108+ life and can confirm, you can avoid all settings that haven't been mentioned on the [blog](https://hhvm.com/blog) at one point or another.

**Comment by AndrewDiMola** [comment]
@lexidor going to sort through the blog, but do you have recommendations on a shortlist of settings that would be useful in a v.1 page?

**Comment by fredemmott** [comment]
> `auto_namespace_map`

FWIW, if we document stuff like this, we should have a big warning saying that it should not be used in public projects where you expect others to depend on it. For example, open source libraries should never use this.

This is because:
- it requires global, not per-project configuration, both in HHVM and the typechecker
- there is no conflict resolution method. If one project has `Foo` => `SomeCorp\Foo` and another has `Foo` => `SomeOtherCorp\Foo`, this can not be resolved.

I'm not against documenting it, and I wouldn't really call it discouraged in the situations where it is not problematic, but we need to be very clear about when it's appropriate, and that it's not a 'best practice' (or an antipattern)

**Comment by lexidor** [comment]
> For example, open source libraries should never use this.

Agreed, I should have to mess with my hhvm and hhconfig configuration to `composer require happycorp/yaml-parser`. Just a convenience feature for monorepos and top level applications.

**Comment by connordoner** [comment]
> “auto_namespace_map”

Truthfully, I was blissfully unaware of this setting, which underscores why documentation is so important! Good spot, @lexidor.

**Comment by connordoner** [comment]
Where are we up to on this?

**Comment by connordoner** [comment]
It seems there's been nothing further on this so, unless I have any opposition, I'm going to close it for now.
