### ISSUE TITLE
HHVM test runner improvements for our test suite.

### ISSUE THREAD

**Issue by JoelMarcey** [hhvm/user-documentation#194]
Modify HHVM test runner to support passing both HHVM and hh_server binary

Also make sure that `hhvm_path()` isn't called unneccessarily in typechecker mode. Test by running  on a big directory of --typechecker (like the doc test suite) tests so it spawns subprocesses.

**Comment by fredemmott** [comment]
- When spawning subprocesses, we should probably always use PHP_BINARY instead of the CLI arguments - the arguments say what we're testing, not what should be used to run the test runner, and it's weird for subproccesses to use a different HHVM to the main one
 - Should this be an issue against the HHVM repo instead?

**Comment by AndrewDiMola** [comment]
Trying to understand context here -- is this something we should direct attention to still? or move?

**Comment by Wilfred** [comment]
Given the age of this task, I'm inclined to close this. I'm not aware of any issues with the test runner these days. Feel free to reopen if you have specific details in mind.
