### ISSUE TITLE
Possibly add link to API reference in header

### ISSUE THREAD

**Issue by JoelMarcey** [hhvm/user-documentation#204]
I think the API reference is separate and just as important as the guides and deserve a place amongst the header. I am going to add it and see how it looks.

**Comment by fredemmott** [comment]
Which header? I have no problem with the filter, but we intentionally made these a little harder to find because people kept on thinking they just needed a reference, but fundamentally didn't understand what they were working with (especially async, collections)

--
Typed with my thumbs

On Dec 11, 2015, at 08:41, Joel Marcey <notifications@github.com<mailto:notifications@github.com>> wrote:


I think the API reference is separate and just as important as the guides and deserve a place amongst the header. I am going to add it and see how it looks.

**Comment by JoelMarcey** [comment]
![screenshot 2015-12-11 10 24 45](https://cloud.githubusercontent.com/assets/3757713/11751908/71e4640e-9ff1-11e5-8d1e-11bed8bb08d7.png)

**Comment by fredemmott** [comment]
s/filter/footer/

So...
 - this doesn't belong there. API is /part/ of the Hack documentation, and clicking Hack gives you both a list of guides and a link to the API reference
 - this is way too prominent given the problem we wanted to solve by emphasising the guides
