### ISSUE TITLE
Proxygen is no longer supported as of 3.0.0 but it's not stated in documentation

### ISSUE THREAD

**Issue by lhorace** [hhvm/user-documentation#298]
Please complete the information below:

# Where is the problem?

https://docs.hhvm.com/hhvm/basic-usage/proxygen

# What is the problem?

Minor comesitic issue. It appears that Proxygen was depreciated/dropped as of 3.0.0 but you have the impression it's still supported. 

I ran into 'Uncaught exception: no factory for server type "proxygen"\n' and assumed at first I was missing an external library or the HHVM was missing a compiler flag

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2016-03-25T19:44:16+0000:59945858b91b58253f39c91d5ff11f685e228917:ded7f690201f02c37531b00bb6a6fc0091e9945e
 - Page requested: /hhvm/basic-usage/proxygen
 - Page requested at: Tue, 29 Mar 2016 12:09:52 +0000
 - Controller: GuidePageController

**Comment by fredemmott** [comment]
This is not true - the libevent HTTP server was deprecated, but proxygen is still fully supported, and supposed to be included in our official packages - it's *definitely* in 3.12.1's Ubuntu 14.04 package.

 - if you built HHVM yourself, try https://www.facebook.com/groups/hhvm.general/ or #hhvm on Freenode
 - otherwise, file an issue against where ever you got the package from, including your exact HHVM and distribution versions; if it's a package that HHVM ourselves provide, file the issue here: https://github.com/hhvm/packaging

**Comment by lhorace** [comment]
This was the error that was thrown:

Uncaught exception: HHVM no longer supports the built-in webserver as of 3.0.0. Please use your own webserver (nginx or apache) talking to HHV
M over fastcgi. https://github.com/facebook/hhvm/wiki/FastCGI

Compiler: tags/HHVM-3.6.0-0-g6ef13f20da20993dc8bab9eb103f73568618d3e8
Repo schema: 3ab6576af394a33abbb29796c652f06b1c7640ce

So at some point in time the feature was removed, however, if it has been re-introduce in 3.12.1. Then I will upgrade to that version.  At least a notation that one should upgrade to latest available of HHVM because obviously after one has read this. One would assumed that HHVM no longer supported proxygen as of 3.0.0.

Regards.

**Comment by fredemmott** [comment]
- 3.6 is unsupported - at the time, 'the built-in webserver' was the libevent server
 - Proxygen was introduced in 3.8

Only 3.9.2 and 3.12.1 are currently supported - 3.6.0 has known security issues. In the short term, you should migrate to 3.6.6 as soon as possible, however you should migrate to a supported version as soon after as is practical.
