### ISSUE TITLE
Add grouping for guides

### ISSUE THREAD

**Issue by matthewjohnston4** [hhvm/user-documentation#39]
Essentially, we want to be able to do this (ignore the specific titles) with the guides to prioritise visual grouping based on skill level of readers:

![home_grouping](https://cloud.githubusercontent.com/assets/986185/11070010/2840a6b0-87d1-11e5-962f-9ab453a5ea0e.png)

Right now, there's no hierarchy and it's too confusing and intimidating for beginners imo

**Comment by fredemmott** [comment]
Sorry, could you give an example of the specific titles you'd like, rather than just the general idea?

As for the 'how' discussion: depending on how many items per category etc, I'd probably much rather use the directory structure for this than marker files:

 - it would match the existing behavior
 - navigating to the source files would match navigating to it in the website
 - all files in a category would be in the same place

**Comment by fredemmott** [comment]
+ as matthew said in the chat, it also makes renaming categories cleaner than having content in the files.

**Comment by matthewjohnston4** [comment]
Currently I'd group them thusly:
### Hack
#### Quickstart:
 + Getting Started 
 + Tools
 + FAQ

#### Basics:
 + Types
 + Async
 + Collections
 + XHP
 + Typechecker

### Advanced:
 + Everything Else

I'm open to argument about what fits into each of these categories, but I think they're the right buckets at least.

**Comment by fredemmott** [comment]
Might revisit depending on user feedback, but as we've launched and things seem OK, closing for now.
