### ISSUE TITLE
On Chrome 61 Linux left navigation covers the content

### ISSUE THREAD

**Issue by bmarkovic** [hhvm/user-documentation#458]
Please complete the information below:

# Where is the problem?

Entire documentation.

# What is the problem?

Until the page is  **fully** loaded, which here takes tens of seconds for the last bit of JavaScript or CSS, whatever is causing it, to load and be interpreted, left sidebar is covering the content -- thus making the page unusable. I think that page resources should be refactored so that the bits that the layout depends on load first, or preferably with the page itself.

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2017-08-30T21:18:06+0000:8cd4e0ba1b69cd6f886c69105cc88494eff5691a:688fc658056e4f639625475a4fb92cfae15b46a4
 - Page requested: /hhvm/FAQ/faq
 - Page requested at: Thu, 14 Sep 2017 06:01:05 +0000
 - Controller: GuidePageController

**Comment by AndrewDiMola** [comment]
Closing because the docs site has undergone many refactors in the last 5 year and I believe this is no longer an issue.

@bmarkovic If the sidebar is still covering content because of site speeds, please reopen and let me know. If anyone else is experiencing this same issue, please also comment here.
