### ISSUE TITLE
document the spaceship operator

### ISSUE THREAD

**Issue by fredemmott** [hhvm/user-documentation#461]
Please complete the information below:

# Where is the problem?

the bit about PHP operators

# What is the problem?

it says the typechecker doesn't support the spaceship operator; this is no longer true.

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2017-08-30T21:18:06+0000:8cd4e0ba1b69cd6f886c69105cc88494eff5691a:688fc658056e4f639625475a4fb92cfae15b46a4
 - Page requested: /hack/operators/introduction
 - Page requested at: Fri, 22 Sep 2017 23:50:39 +0000
 - Controller: GuidePageController

**Comment by RexJaeschke** [comment]
I have nearly completed a major revision of the Hack Tutorial site. 

W.r.t the spaceship operator, the new edition will contain the following:

Often referred to as the *spaceship operator*, the binary operator `<=>` compares the values of its operands and returns an `int` result. If the left-hand value is less than the right-hand value, the result is some unspecified negative value; else, if the left-hand value is greater than the right-hand value, the result is some unspecified positive value; otherwise, the values are equal and the result is zero. For example:

```Hack
1 <=> 1         // 0; equal
1 <=> 2         // negative; 1 < 2
2 <=> 1         // positive; 2 > 1

"a" <=> "a"     // 0; same length and content
"a" <=> "b"     // negative; a is lower than b in the collating sequence
"b" <=> "a"     // positive; b is higher than a in the collating sequence
"a" <=> "A"     // positive; lowercase a is higher than uppercase A

"a" <=> "aa"    // negative; same leading part, but a is shorter than aa
"aa" <=> "a"    // positive; same leading part, but aa is longer than a
"aa" <=> "aa"   // 0; same length and content
```
