### ISSUE TITLE
Cant start HHVM completely

### ISSUE THREAD

**Issue by GroeGIT** [hhvm/user-documentation#482]
# Where is the problem?

HHVM daemon

# What is the problem?

After installing everything on Ubuntu Server 16, my testfile shows that HHVM is not started.
At the same time  `sudo service hhvm status` tells me that the status is active (exited) and that it cannot open /var/log/hhvm/error.log

restarting the server gives no errors but i can not get HHVM completely up and running.
The testfile is a simple if/else PHP file in var/www/html like the following.

`<?php 

if (defined('HHVM_VERSION')) {

    echo 'hhvm is working';

} else {

    echo 'hhvm is not working' ;

}
?>`

I used the official installation guide.
How can i fix this?
--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: 2017-11-23T07:45:10+0000:2555282b8f6ccf911b335e1d4f3b976dc5bfc9b0
 - Page requested: /hhvm/installation/linux
 - Page requested at: Fri, 08 Dec 2017 13:20:12 +0000
 - Controller: GuidePageController

**Comment by fredemmott** [comment]
This is probably https://github.com/hhvm/packaging/issues/159

**Comment by GroeGIT** [comment]
Nope, already applied that fix. It starts normally now, but my testpage still says HHVM is not working.

**Comment by fredemmott** [comment]
If you're literally getting `hhvm is not working` without any of the other code, you need to configure your webserver to prefer HHVM to PHP; you'll need to look in to your webserver (likely apache or nginx) documentation.

Alternatively, if you're not trying to use HHVM as a drop-in replacement for an existing system, it will likely be easier to use HHVM's built in webserver:

 - if you don't care about running it as a service, `hhvm -m server -p 8080` starts the server on port 8080
 - otherwise, change your configuration file to set `hhvm.server.type` to `proxygen` (or just unset it), and set `hhvm.server.port` to a free port, and restart the hhvm service

If you are trying to drop it into an existing PHP service, you probably want to read hhvm.com/blog/2017/09/18/the-future-of-hhvm.html if you haven't already.

**Comment by GroeGIT** [comment]
I am trying to use HHVm as a secure way to run a existing PHP7 application on some external servers(owned by the clients). But i think HHVM is not completely the solution to my security issues.(client stealing or modifying code) so i think i will pass and search for a more secure way of deploying and running the code.
