### ISSUE TITLE
Document Traversable differences vs PHP

### ISSUE THREAD

**Issue by muglug** [hhvm/user-documentation#568]
It seems like `Traversable` acts a lot like PHP's `iterable`, insofar as this is valid:

```php
<?hh
function foo(Traversable<int> $t) {}
foo([1, 2, 3]);
```

**Comment by muglug** [comment]
> I'll make sure the principle is covered in the new docs, but we are moving from 'describe the differences' to 'describe the language'.

I get the difficulty there, ReasonML's docs strike a decent balance - it's designed to be easy for JS devs to pick up, and their docs frequently draw comparisons between the two, without just describing the differences

**Comment by lexidor** [comment]
The PHP `\Traversable` interface has been removed. Only the Hack specific interface `\HH\Traversable<T>` remains. https://hhvm.com/blog/2019/11/19/hhvm-4.32.html

This confusion existed because the `\HH\Traversable<T>` interface is automatically imported. This meant that Hack developers have been using the HH variant without knowing about it.
