### ISSUE TITLE
Inconsistent behavior of hhvm and description in Type: Shapes

### ISSUE THREAD

**Issue by zhutianqi** [hhvm/user-documentation#651]
https://docs.hhvm.com/hack/types/shapes
**In the very last paragraph:**

"Note carefully, that inside function process_transaction, even though the transaction passed in might have been a Deposit, a Withdrawal, or a Transfer, it always appears as a Transaction, so the only field we can access in $t is trtype. However, using Shapes::toArray, we can convert the Transaction to an array, and then get read-access to the field values we know that array must contain by indexing it using the field names, as shown."

**When I run it locally, I find out that even we don't change Shape to Array, the code still works, which contradicts the description.**

**Comment by Wilfred** [comment]
OK, so if I change the code as you describe:

```
function process_transaction(Transaction $t): void {
  $ary = $t;
  switch ($t['trtype']) {
  case Bank::TRANSFER:
    echo "Transfer: " . ((string)$ary['amount'])
      . " from Account " . ((string)$ary['fromaccnum'])
      . " to Account " . ((string)$ary['toaccnum']) . "\n";
    // ...
    break;

  case Bank::DEPOSIT:
    echo "Deposit: " . ((string)$ary['amount'])
      . " to Account " . ((string)$ary['toaccnum']) . "\n";
    // ...
    break;

  case Bank::WITHDRAWAL:
    echo "Withdrawal: " . ((string)$ary['amount'])
      . " from Account " . ((string)$ary['fromaccnum']) . "\n";
    // ...
    break;
  }
}
```

This runs without error today, as you say. However, the type checker rejects it.

Today the underlying data representation is the same, so `Shapes::toArray` doesn't actually change the data at runtime. That's why this works. Hack is unusual in that (today at least) you can run code that the type checker rejects (although we don't generally make any guarantees about the behaviour).

I think the docs are correct here, since this section is about the type checker, and this is a general restriction on the type checker. I'm happy to change the wording if you think that's worthwhile though.
