### ISSUE TITLE
Time complexity of vec map_with_key incorrect

### ISSUE THREAD

**Issue by paraggangil** [hhvm/user-documentation#675]
Please complete the information below:

# Where is the problem?

The time complexity of vec map_with_key seems to be independent of the complexity of $value_func which is incorrect. It should be something like this: https://docs.hhvm.com/hsl/reference/function/HH.Lib.Dict.map_with_key/
# What is the problem?

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: HHVM=HHVM-4.10.0:HSL=v4.7.0:2019-06-25T01:07:41+0000:24194533a68f50062246986e35b8afb154180909
 - Page requested: /hsl/reference/function/HH.Lib.Vec.map_with_key/
 - Page requested at: Thu, 04 Jul 2019 12:25:22 +0000
 - Controller: APIClassPageController

**Comment by Wilfred** [comment]
OK, so `Vec\map_with_key` [docs](https://docs.hhvm.com/hsl/reference/function/HH.Lib.Vec.map_with_key/) say the time complexity is O(n), but `Dict\map_with_key` [docs](https://docs.hhvm.com/hsl/reference/function/HH.Lib.Dict.map_with_key/) say O(n * f).

I think both should say O(n), because the time complexity of `f` isn't terribly helpful, and it's not necessary constant (it might vary depending on the input).

**Comment by AndrewDiMola** [comment]
Closing. This was resolved in https://github.com/hhvm/hsl/commit/81df5d30112ce1ea41add19e85e4a44175852a77.
