### ISSUE TITLE
hack suggestion

### ISSUE THREAD

**Issue by gingerdudley** [hhvm/user-documentation#676]
Please complete the information below:

# Where is the problem?

-The section explains the filter function for vectors

# What is the problem?

- I think it would be useful to have an example for this function and how the callback is used. Being new to hack, this was kinda confusing and a code example could've helped. 

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: HHVM=HHVM-4.10.0:HSL=v4.7.0:2019-06-25T01:07:41+0000:24194533a68f50062246986e35b8afb154180909
 - Page requested: /hack/reference/class/HH.Vector/filter/
 - Page requested at: Fri, 12 Jul 2019 16:39:59 +0000
 - Controller: APIMethodPageController

**Comment by lexidor** [comment]
>  Being new to hack, this was kinda confusing and a code example could've helped.

Hi, welcome. Thank you for showing interest and opening an issue on this repo.

> I think it would be useful to have an example for this function and how the callback is used.

The strange thing is, there is already an example file. I don't quite understand why [this example](https://github.com/hhvm/user-documentation/blob/master/api-examples/class.HH.Vector/filter/001-basic-usage.php) is not shown to you. I'll try to get in touch with someone who knows how the build system of this website works and why this example may be missing.

A general note about the types `HH\Vec`, `HH\Map`, `HH\Set` and their immutable counter parts.
HHVM has had these Collection classes since launch. Even though they can still be used, I would like to refer you to their newer, better, value type versions. HHVM comes with `vec`, `dict`, and `keyset`. These are the friends of `Vector`, `Map` and `Set` respectively. They are a lot more flexible in how and when they can be used.

In order to make full use of these types, you should take a look at [the hack standard library](https://github.com/hhvm/hsl). You can install this through composer. `php composer.phar require hhvm/hsl` I would love to offer you a helping hand if you get stuck.

```HACK
use namespace HH\Lib\Vec;
<<__EntryPoint>>
function example(): noreturn{
  $users_older_than_18 = vec[400, 404, 500] |>
    Vec\map($$, $id ==> User::getById($id)) |>
    Vec\filter($$, $user ==> $user->getAge() > 18);
  //...
  exit();
}
```

**Comment by fredemmott** [comment]
#699 addresses this

**Comment by Wilfred** [comment]
#699 is merged and https://docs.hhvm.com/hack/reference/class/HH.Vector/filter/ is showing examples :)
