### ISSUE TITLE
Program structure partial not reflected as special recognized comment

### ISSUE THREAD

**Issue by MathBunny** [hhvm/user-documentation#774]
Please complete the information below:

# Where is the problem?
https://docs.hhvm.com/hack/source-code-fundamentals/comments

# What is the problem?

I may be wrong, but under [special recognized comments](https://docs.hhvm.com/hack/source-code-fundamentals/comments) `// partial` is not mentioned, despite it being listed on the  [program structure](https://docs.hhvm.com/hack/source-code-fundamentals/program-structure) page alongside `// strict`. Thanks!

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: HHVM=HHVM-4.36.0:HSL=v4.36.0:2019-12-30T17:14:57+0000:2fbf0284beeb3f9eaf249c1cefcabcd98d115e74
 - Page requested: /hack/source-code-fundamentals/comments
 - Page requested at: Tue, 31 Dec 2019 21:51:49 +0000
 - Controller: GuidePageController

**Comment by jjergus** [comment]
Good catch, thanks!

**Comment by fredemmott** [comment]
Yeah, this should be changed, but very clearly discouraged: it was an intentional decision to *only* document strict mode as much as possible (and later, to only document `.hack` files as much as possible), but there is a conflicting need to people to be able to find answers to "what does this thing I saw in this file mean?"

**Comment by jjergus** [comment]
> Yeah, this should be changed, but very clearly discouraged

It links to a page that discusses all that so I think it should be fine.
