### ISSUE TITLE
implicit brake in switch statement

### ISSUE THREAD

**Issue by ajaxboy** [hhvm/user-documentation#789]
Please complete the information below:

# Where is the problem?

no implicit brake in case's switch statement

This is more like an improvement request

# What is the problem?

Each case requires brakes on each case in order to skip the later cases, This is redundant.  
Wouldn't it make sense if the brake keyword would be implicit on each switch case?
For instance, this is the default in languages like Golang  - and I think it makes perfect sense.

Instead you can add something like "continue" which would allow to pass to the next cases. 

With new introduction of spaceship operator, shorter lambdas statements, and even shorter shorthand if statements; this would make some justice to the switch statement.

I understand that this would brake possibly many apps; where an omitted brake is intended to pass to the next case, here it would stop executing the the later cases.  Backward compatibility of course should always be a priority, but where do we draw the line?

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: HHVM=HHVM-4.40.0:HSL=v4.40.0:2020-01-17T14:02:04+0000:9f1d392f2f951dfdad225c21329bf894f6577f36
 - Page requested: /hack/statements/switch
 - Page requested at: Sun, 26 Jan 2020 07:21:30 +0000
 - Controller: GuidePageController

**Comment by fredemmott** [comment]
I think we're very unlikely to change this behavior due to the huge amount of existing code; additionally, `continue` is not currently usable due to behavior inherited from PHP (`switch` is implemented as a loop construct - which can be very confusing when a switch is inside a loop)

If you feel strongly about this, please reopen at https://github.com/facebook/hhvm/issues/new/choose - this isn't a documentation issue
