### ISSUE TITLE
Add explanation on how to require HSL and how to use it

### ISSUE THREAD

**Issue by xixixao** [hhvm/user-documentation#796]
Please complete the information below:

# Where is the problem?

On this page

# What is the problem?

At this point the dev likely doesn't understand well how to use composer, plus the page doesn't say what the actual namespaced name of the libraries are. Can we add `composer require hhvm/hsl hhvm/hsl-experimental` here? The `hsl` require step is on previous page in the get started series, but it can be easily missed (that page with large block of CLI output isn't great either).

Secondly, from here on, in the examples on next page the namespaces are used aliased, like `IO\request_output();` on https://docs.hhvm.com/hack/getting-started/input-and-output . But that doesn't actually work if you follow the steps in the docs, you need to use the full name. Can we add info on how to alias them right here?

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: HHVM=HHVM-4.42.0:HSL=v4.40.0:2020-02-04T12:45:10+0000:3c1f3d4e182eaecd809db77f5b43bced324cc2fb
 - Page requested: /hack/getting-started/the-standard-library
 - Page requested at: Wed, 05 Feb 2020 04:52:26 +0000
 - Controller: GuidePageController

**Comment by jjergus** [comment]
> Can we add composer require hhvm/hsl hhvm/hsl-experimental here?

It feels redundant to me to include Composer instructions in every introductory article, I think it's probably reasonable to expect people who are reading the introduction to look at other introductory sections when they need more information... The GitHub README for most projects also has the Composer command, which is another place where I think we can reasonably expect people to look for it. Although I noticed it's missing from the hsl-experimental README, I should fix that.

> that page with large block of CLI output isn't great either

Agreed, I'll try to improve that section.

> Can we add info on how to alias them right here?

We automatically strip boilerplate from examples because for most examples it's distracting and not relevant, but I agree we should keep it in introductory examples like this. I'll fix that.

**Comment by jjergus** [comment]
also https://github.com/hhvm/hsl-experimental/pull/111
