### ISSUE TITLE
Exec format Error

### ISSUE THREAD

**Issue by ghost** [hhvm/user-documentation#835]
Please complete the information below:

# Where is the problem?

 WSL Debian 10 buster

# What is the problem?

Run hhvm called Error: Exec format Error

--------------------------------

Please don't change anything below this point.

--------------------------------

 - Build ID: HHVM=HHVM-4.48.0:HSL=v4.40.0:2020-03-16T17:42:14+0000:f8302ee3b88d741f5476f814a6e517c5568a2e81
 - Page requested: /hhvm/getting-started/getting-started
 - Page requested at: Thu, 19 Mar 2020 14:41:30 +0000
 - Controller: GuidePageController

**Comment by AndrewDiMola** [comment]
Sorry for the lack of a response here. 

Closing this issue because of the amount of time that's elapsed, but if you're still looking to support HHVM on 10 / buster, you can re-open and I can try and help you out further. Actively, we currently support 11 / bullseye if you're able to try one of the latest releases.
