### ISSUE TITLE
AsyncMysql tests have been skipped since hhvm 4.9 (removal of mysqli)

### ISSUE THREAD

**Issue by lexidor** [hhvm/user-documentation#910]
This statement dies with the message `Fail` since hhvm 4.9.0, when mysqli was removed.

api-examples/__includes/async_mysql_require_env.inc.php
```HACK
if (!extension_loaded('mysql') || !function_exists('mysqli_connect')) {
  die('Skip');
}
```

**Comment by jjergus** [comment]
Even worse, I recently found out we don't actually typecheck or run any examples from `api-examples/...` (only from `guides/...`). I have it on a list of things to fix after the XHP update lands (#901).

This one should have been caught by the typechecker because it calls `mysqli_connect` later, which doesn't exist. However, this example also depends on a running MySQL server with the exact DB+table contents, so I'm not sure if there's any good way to fix it even if we updated it to use async-mysql instead of mysqli :(

**Comment by fredemmott** [comment]
So, these tests at least used to be runnable if you set the correct environment variables

While this is a pain, we should consider making it 'just work' in dockerized dev/test environments (including CI), with a memory-backed mysql instance

**Comment by lexidor** [comment]
> This one should have been caught by the typechecker because it calls mysqli_connect later, which doesn't exist.

This is top level code in a `// partial` file, so it isn't typechecked...

**Comment by fredemmott** [comment]
We should consistently kill all .php files from the examples, except for a 'legacy features' example :)
