### ISSUE TITLE
Update /hhvm/installation/release-schedule

### ISSUE THREAD

**Issue by bigfootjon** [hhvm/user-documentation#939]
Support [recently ended for 4.32](https://hhvm.com/blog/2020/10/21/hhvm-4.80.html).

I can update [the source](https://github.com/hhvm/user-documentation/blob/master/guides/hhvm/01-installation/06-release-schedule.md) and submit a PR, but I wasn't sure about the expected future LTS versions.

**Comment by jjergus** [comment]
Good catch. I think ideally we should rephrase that page so that we don't have to update it after every LTS release, something like

> Here's a list of recent LTS releases as well as planned future LTS releases:
> --table with version numbers/(expected) release date/(expected) end of support--

The release dates and version numbers are very regular, it's always +24 weeks and +24 minor version number. We actually skip a version number if we ever skip a weekly release for any reason, just so that it stays regular.
