### ISSUE TITLE
Use inclusive terms in user-documentation

### ISSUE THREAD

**Issue by dhawal55** [hhvm/user-documentation#955]
# Where is the problem?

The below sections use non-inclusive terminology like "whitelist". Please replace it with inclusive terminology "allowlist"

- Getting Started: Starting A Real Project
- Silencing Errors: Introduction
- Advanced Usage: Repo Authoritative
- Configuration: INI Settings

# What is the problem?

While the terms "whitelist" and "blacklist" are commonly used, it casually assigns positive connotations to "white" while assigning negative connotations to "black". I recommend using inclusive terminologies like "allowlist" and "denylist" instead.

 - Build ID: HHVM=HHVM-4.84.0:HSL=v4.41.0:2020-11-18T21:55:19+0000:1fa47f258c6b68f8ec01899aa82fd6ffa0957109
 - Page requested: /hack/getting-started/starting-a-real-project
 - Page requested at: Mon, 23 Nov 2020 23:15:54 +0000
 - Controller: GuidePageController

**Comment by jjergus** [comment]
I appreciate the concern, but this doesn't seem like a valuable use of anyone's time. If you feel strongly, feel free to send a PR, otherwise I'm just going to close this for now.

If you do decide to send a PR, I'd recommend trying to find a better term than "allowlist", I think in most cases there should be a more descriptive term based on each specific usage like "list of ..." (for the hhconfig option, you could just use the actual option name, which I believe doesn't contain any of the terms you dislike).
