### ISSUE TITLE
API example files sometimes not being regenerated when they need to be

### ISSUE THREAD

**Issue by fredemmott** [hhvm/user-documentation#982]
1. I did the change in https://github.com/hhvm/user-documentation/pull/980/commits/3189fc33c320de182191c8ecaf9c5102ea0e0f54
2. I ran build.php, no new skipif locally
3. CI detected the missing skipif
4. I tried deleting build/extracted-examples/ and re-building, still no new skipif
5. I tried deleting build/{final,scracth} and rebuilding - now have new skipif

Step 2 should have generated the skipifs. 4 and 5 hint at the cause

**Comment by jjergus** [comment]
The caching (`HHAPIDocBuildStep::shouldSkip`) is causing this.

```
2021-01-26 12:32:29] HHAPIDocBuildStep
2021-01-26 12:32:29] ...already built and no dependencies changed, skipping.
```

(actually not a new issue, it has been broken since I added the caching years ago, just no one touched these examples since then :/)

I'll probably just remove it for now, but if the build becomes significantly slower, we could cache everything in `HHAPIDocBuildStep` up to "Writing index file", just not the final 2 "Generating Markdown" steps.

**Comment by fredemmott** [comment]
Ah - `getTagFileContent()` probably needs changing to include any manual .md file mtimes or similar, not just the tags for the repositories we fetch

**Comment by fredemmott** [comment]
(and previously this should have been the .php and .example.out and .expect files)
